Statistics added
Darderion/map pull request #18
Opened 2022-03-31 11:59 UTC by Liana2707

2022-04-05 11:21 UTC, Darderion requested changes

2022-04-05 11:21 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/pdfdocument/PDFDocument.kt
> +			val documentSize = pdfSize
![tumblr_8bc50ff60f567ed7ad3bd29e9eaa75e0_de48e27f_400](https://user-images.githubusercontent.com/36251589/161740289-e750bf5f-5a18-4978-8dbe-93c64d8150b6.png)

2022-04-05 11:21 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/checker/Checker.kt
> +	fun getPDFStatistic(pdfName: String) : Statistic {
Checker class should check PDF for rule violations

Suggestion: Add StatisticsService or a similar class that handles acquiring statistics

2022-04-05 11:21 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/checker/statistics/SectionStatistics.kt
> +data class SectionStatistics(var section: Section, var sectionSizeInPage: Int,
"sectionSizeInPercents" can be calculated based on two other properties

2022-04-05 11:21 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/checker/statistics/SectionStatistics.kt
> +                             var sectionSizeInPercents: Float, var documentSize:Int)
"Val" should be used by default as it makes code a lot more clear about which properties can change and which fields stay the same after the construction of an object

2022-04-05 11:21 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/pdfdocument/PDFDocument.kt
> +		val pdfsections = PDFStructure(text).sections
camelCase

2022-04-12 12:58 UTC, Liana2707 commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/pdfdocument/PDFDocument.kt
> +	fun getWordsStatistic() : WordsStatistic
Done

2022-04-22 02:59 UTC, merged