UrlUniformityRule added
Darderion/map pull request #20
Opened 2022-04-01 12:06 UTC by gwyndol1ne

2022-04-08 19:53 UTC, Darderion requested changes

2022-04-08 19:53 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/rules/Rules.kt
> +			filteredUrls.filter {	pair ->
Filter method doesn't change filteredUrls

2022-04-08 19:53 UTC, Darderion commented on src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/RulesTests.kt
> +		RULE_URLS_UNIFORMITY.process(PDFBox().getPDF(filePathUniformityUrls)).count() shouldBeExactly 1
Test doesn't match rule's violations

2022-04-15 11:40 UTC, gwyndol1ne commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/rules/Rules.kt
> +			filteredUrls.filter {	pair ->
updated

2022-04-15 11:40 UTC, gwyndol1ne commented on src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/RulesTests.kt
> +		RULE_URLS_UNIFORMITY.process(PDFBox().getPDF(filePathUniformityUrls)).count() shouldBeExactly 1
updated

2022-04-22 02:53 UTC, merged