Dev sections order
Darderion/map pull request #21
Opened 2022-04-01 17:44 UTC by alex-tinarsky

Added SectionsOrderRule

2022-04-08 19:41 UTC, Darderion requested changes

2022-04-08 19:41 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/rules/Rules.kt
> +	"Введение" to hashSetOf(""),
Could be replaced with INTRODUCTION as it is used in multiple places

2022-04-08 19:41 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/rules/Rules.kt
> +	"Постановка задачи" to hashSetOf("Введение"),
https://github.com/Darderion/map/pull/9#discussion_r824535710

2022-04-08 19:41 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/rules/Rules.kt
> +					.filterNot { it.text.contains("[0-9]+\\.".toRegex()) }
https://github.com/Darderion/map/pull/18#discussion_r842637313

2022-04-11 15:50 UTC, alex-tinarsky commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/rules/Rules.kt
> +					.filterNot { it.text.contains("[0-9]+\\.".toRegex()) }
Done

2022-04-22 02:47 UTC, merged