Dev quotes rule
Darderion/map pull request #3
Opened 2022-02-16 15:09 UTC by alex-tinarsky

2022-02-16 16:22 UTC, chernishev commented
You should provide description for your PR, similarly to e.g. https://github.com/Mstrutov/Desbordante/pull/50

2022-02-17 17:03 UTC, Darderion requested changes

2022-02-21 08:27 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/checker/rule/symbol/BasicSymbolRule.kt
> +import kotlin.reflect.jvm.internal.impl.utils.DFS.Neighbors
?

2022-02-21 09:11 UTC, Darderion approved these changes
![Achievement 2022-02-21 090931](https://user-images.githubusercontent.com/36251589/154923507-b98c8b69-8fe4-46ef-8e5a-ea7ac42f09f7.png)
![Achievement 2022-02-21 090150](https://user-images.githubusercontent.com/36251589/154923531-b6b6c90e-12e9-4418-9447-21c830e598c7.png)

2022-02-21 09:13 UTC, merged