RuCapitallLettersAfterBracketRule and MultiLinksRule added
Darderion/map pull request #4
Opened 2022-02-18 16:15 UTC by gwyndol1ne

2022-02-18 17:22 UTC, Darderion requested changes
![image](https://user-images.githubusercontent.com/36251589/154731554-3e1cd77b-6210-4ddf-89c2-b204e351d639.png)
?

2022-02-18 17:22 UTC, Darderion commented on src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/SymbolRuleTests.kt
> +			.fromRight().shouldNotHaveNeighbor(*"[".toCharArray())
`*"[".toCharArray()` -> `'['`

2022-02-18 17:22 UTC, Darderion commented on src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/SymbolRuleTests.kt
> +		const val filePath3 = "${resourceFolder}checker/LargeRussianLetterTests.pdf"
If a test file contains multiple PDF files then filePaths have to be just as descriptive as their file names. Furthermore, files have to match their tests by adhering to naming conventions already present in a project
(Example: https://github.com/Darderion/map/blob/master/src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/ListRuleTests.kt)

2022-02-18 17:22 UTC, Darderion commented on src/test/resources/com/github/darderion/mundaneassignmentpolice/checker/.~lock.MultipleLinksRuleTest.pdf#
> +,gwyndol1ne,gwyndol1ne,18.02.2022 18:59,file:///home/gwyndol1ne/.config/libreoffice/4;
?

2022-02-18 17:22 UTC, Darderion commented on src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/SymbolRuleTests.kt
> +	"Symbol rule should detect incorrect using multiple links" {
"Symbol rule should detect incorrect using multiple links" -> "Symbol rule should detect incorrect use of multiple links"

2022-02-18 17:22 UTC, Darderion commented on src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/SymbolRuleTests.kt
> +	"Symbol rule should detect incorrect using multiple links" {
Two tests with the same name

2022-02-23 18:09 UTC, gwyndol1ne reviewed
Updated rules

2022-02-24 15:09 UTC, Darderion commented on src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/SymbolRuleTests.kt
> +	"Symbol rule should detect incorrect using capital letters" {
"usage of letters"

2022-02-24 15:46 UTC, merged