Dev small numbers rule
Darderion/map pull request #5
Opened 2022-02-22 14:45 UTC by alex-tinarsky

Added rule to detect writing integers from one to nine as digits instead of words.

2022-02-23 13:23 UTC, Darderion requested changes

2022-02-23 13:23 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/checker/Checker.kt
> +				.fromRight().shouldNotHaveNeighbor(*" \n,;:?$".toCharArray()).getRule())
"-Vous avez dit que vous n’étiez que trois, mais il me semble, à moi, que nous sommes 4." -- extrait de "Trois Mousquetaires"

Suggestion: "ignoringAdjusting(SYMBOLS)"

2022-02-23 13:23 UTC, Darderion commented on src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/SymbolRuleTests.kt
> +		numberOfRuleViolations shouldBeExactly 2
Quotes are not tested
Brackets are not tested
Footnotes are not tested

2022-02-23 13:23 UTC, Darderion commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/checker/Checker.kt
> +			smallNumbersRuleBuilder.symbol("$i".toCharArray().first())
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/digit-to-char.html

2022-02-27 22:12 UTC, alex-tinarsky commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/checker/Checker.kt
> +			smallNumbersRuleBuilder.symbol("$i".toCharArray().first())
Applied

2022-02-27 22:13 UTC, alex-tinarsky commented on src/test/kotlin/com/github/darderion/mundaneassignmentpolice/checker/SymbolRuleTests.kt
> +		numberOfRuleViolations shouldBeExactly 2
All of this is being tested now.

2022-02-27 22:13 UTC, alex-tinarsky commented on src/main/kotlin/com/github/darderion/mundaneassignmentpolice/checker/Checker.kt
> +				.fromRight().shouldNotHaveNeighbor(*" \n,;:?$".toCharArray()).getRule())
Fixed

2022-03-02 22:08 UTC, merged