Sections view and Statistics view added
Darderion/map pull request #75
Opened 2024-01-26 17:26 UTC by gwyndol1ne

2024-02-16 01:45 UTC, Darderion requested changes

2024-02-16 01:45 UTC, Darderion commented on src/main/webapp/src/components/RuleViolationsHeader/RuleViolationsHeader.tsx
> +        </Tabs.Panel>
Inconsistent indentations

2024-02-16 01:45 UTC, Darderion commented on src/main/webapp/src/components/Sections/PDFLine.tsx
> +    let index = 0;
Could replace a verbose switch case with an object representing a dictionary

2024-02-16 01:45 UTC, Darderion commented on src/main/webapp/src/components/Sections/PDFLine.tsx
> +export default PDFLines;
Refrain from ignoring warning Github provides, such as "no newline character"

2024-02-16 01:45 UTC, Darderion commented on src/main/webapp/src/components/Statistics/Statistics.tsx
> +        const sortedWords:any = Object.entries(res.data.wordsStatistic.topKWords)
Use appropriate types

2024-02-16 01:45 UTC, Darderion commented on src/main/webapp/src/components/Statistics/Statistics.tsx
> +        setWordCount(res.data.wordsStatistic.wordCount);
Refrain from using trailing whitespaces

2024-05-02 10:06 UTC, gwyndol1ne commented on src/main/webapp/src/components/RuleViolationsHeader/RuleViolationsHeader.tsx
> +        </Tabs.Panel>
.

2024-05-02 10:07 UTC, gwyndol1ne commented on src/main/webapp/src/components/Sections/PDFLine.tsx
> +    let index = 0;
.

2024-05-02 10:07 UTC, gwyndol1ne commented on src/main/webapp/src/components/Sections/PDFLine.tsx
> +export default PDFLines;
.

2024-05-02 10:07 UTC, gwyndol1ne commented on src/main/webapp/src/components/Statistics/Statistics.tsx
> +        const sortedWords:any = Object.entries(res.data.wordsStatistic.topKWords)
.

2024-05-02 10:07 UTC, gwyndol1ne commented on src/main/webapp/src/components/Statistics/Statistics.tsx
> +        setWordCount(res.data.wordsStatistic.wordCount);
.

2024-05-02 11:36 UTC, Darderion approved these changes

2024-05-02 11:36 UTC, merged